version: "1.0"
services:
    Judge:
        build: .
        environment:
            SESSDATA: ""            # SESSDATA变量，即cookie中的同名项
            csrf: ""                # csrf变量，即cookie中的bili_jct
            GiveUpEnable: "True"    # 放弃选项
            delay: 300              # 无法判断时等待时长（仅在GiveUpEnable被设置为False时有效）
            JudgeProportion: 0.7    # 判定比例
